
#include "_locale.h"

const char* TXT_NO_ERROR = "Nessun errore";
const char* TXT_CARD_MOUNT_FAILED = "Impossibile caricare la scheda SD";
const char* TXT_NO_SD_CARD_ATTACHED = "Nessuna scheda SD collegata";
const char* TXT_UNKNOWN_SD_CARD_TYPE = "Tipo di scheda SD sconosciuto";
const char* TXT_CARD_OPEN_FILE_FAILED = "Apertura del file della scheda fallita";
const char* TXT_SD_CARD_FILE_NOT_FOUND = "File della scheda SD non trovato";
const char* TXT_SD_CARD_FILE_OPEN_FAILED = "Apertura del file della scheda SD fallita";
const char* TXT_IMAGE_FORMAT_NOT_SUPPORTED = "Formato immagine non supportato";
const char* TXT_ERROR_CODE = "Codice errore: ";
const char* TXT_BATTERY_LEVEL_CRITICAL = "Livello batteria critico";
const char* TXT_CARD_TOC_OPEN_FILE_FAILED = "Apertura del file TOC della scheda fallita";
const char* TXT_PREFERENCES_OPEN_FAILED = "Apertura delle preferenze fallita";
const char* TXT_NO_IMAGES_FOUND = "Nessuna immagine trovata";