
#include "_locale.h"

const char* TXT_NO_ERROR = "No error";
const char* TXT_CARD_MOUNT_FAILED = "Failed to mount SD card";
const char* TXT_NO_SD_CARD_ATTACHED = "No SD card attached";
const char* TXT_UNKNOWN_SD_CARD_TYPE = "Unknown SD card type";
const char* TXT_CARD_OPEN_FILE_FAILED = "Failed to open SD card file";
const char* TXT_SD_CARD_FILE_NOT_FOUND = "SD card file not found";
const char* TXT_SD_CARD_FILE_OPEN_FAILED = "Failed to open SD card file";
const char* TXT_IMAGE_FORMAT_NOT_SUPPORTED = "Image format not supported";
const char* TXT_ERROR_CODE = "Error code: ";
const char* TXT_BATTERY_LEVEL_CRITICAL = "Battery level critical";
const char* TXT_CARD_TOC_OPEN_FILE_FAILED = "Failed to open SD card TOC file";
const char* TXT_PREFERENCES_OPEN_FAILED = "Failed to open preferences";
const char* TXT_NO_IMAGES_FOUND = "No images found";
const char* TXT_BATTERY_EMPTY = "Battery empty";
const char* TXT_RTC_MODULE_NOT_FOUND = "RTC module not found";