
#include "_locale.h"

const char* TXT_NO_ERROR = "No error";
const char* TXT_CARD_MOUNT_FAILED = "Failed to mount SD card";
const char* TXT_NO_SD_CARD_ATTACHED = "No SD card attached";
const char* TXT_UNKNOWN_SD_CARD_TYPE = "Unknown SD card type";
const char* TXT_CARD_OPEN_FILE_FAILED = "Failed to open SD card file";
const char* TXT_SD_CARD_FILE_CREATE_FAILED = "Failed to create SD card file";
const char* TXT_SD_CARD_FILE_NOT_FOUND = "SD card file not found";
const char* TXT_SD_CARD_FILE_OPEN_FAILED = "Failed to open SD card file";
const char* TXT_IMAGE_FORMAT_NOT_SUPPORTED = "Image format not supported";
const char* TXT_ERROR_CODE = "Error code: ";
const char* TXT_BATTERY_LEVEL_CRITICAL = "Battery level critical";
const char* TXT_CARD_TOC_OPEN_FILE_FAILED = "Failed to open SD card TOC file";
const char* TXT_PREFERENCES_OPEN_FAILED = "Failed to open preferences";
const char* TXT_NO_IMAGES_FOUND = "No images found";
const char* TXT_BATTERY_EMPTY = "Battery empty";
const char* TXT_RTC_MODULE_NOT_FOUND = "RTC module not found";
const char* TXT_JWT_CREATION_FAILED = "JWT creation failed";
const char* TXT_HTTP_POST_FAILED = "HTTP POST request failed";
const char* TXT_JSON_PARSE_FAILED = "JSON parsing failed";
const char* TXT_TOKEN_MISSING = "Token missing";
const char* TXT_FILE_OPEN_FAILED = "File open failed";
const char* TXT_HTTP_CONNECT_FAILED = "HTTP connection failed";
const char* TXT_HTTP_GET_FAILED = "HTTP GET request failed";
const char* TXT_DOWNLOAD_FAILED = "Download failed";
const char* TXT_SSL_CERTIFICATE_LOAD_FAILED = "SSL certificate load failed";