// DO NOT MODIFY -- THIS FILE WAS GENERATED BY `python3 final_generate_icons_h.py`

#ifndef __ICONS_H__
#define __ICONS_H__

#include <cstddef>

#include "icons_12x12.h"
#include "icons_16x16.h"
#include "icons_24x24.h"
#include "icons_32x32.h"
#include "icons_48x48.h"
#include "icons_64x64.h"
#include "icons_96x96.h"
#include "icons_128x128.h"
#include "icons_160x160.h"
#include "icons_196x196.h"

typedef enum icon_name {
  battery_alert_0deg,
  error_icon,
  ionizing_radiation_symbol,
  micro_sd_card_0deg,
  warning_icon,
  wi_time_10,
} icon_name_t;

constexpr const unsigned char* getBitmap(icon_name_t icon, size_t size)
{
  switch (icon) {
  case battery_alert_0deg:
    switch (size) {
    case 12: return battery_alert_0deg_12x12;
    case 16: return battery_alert_0deg_16x16;
    case 24: return battery_alert_0deg_24x24;
    case 32: return battery_alert_0deg_32x32;
    case 48: return battery_alert_0deg_48x48;
    case 64: return battery_alert_0deg_64x64;
    case 96: return battery_alert_0deg_96x96;
    case 128: return battery_alert_0deg_128x128;
    case 160: return battery_alert_0deg_160x160;
    case 196: return battery_alert_0deg_196x196;
    default:
      return nullptr;
    }
  case error_icon:
    switch (size) {
    case 12: return error_icon_12x12;
    case 16: return error_icon_16x16;
    case 24: return error_icon_24x24;
    case 32: return error_icon_32x32;
    case 48: return error_icon_48x48;
    case 64: return error_icon_64x64;
    case 96: return error_icon_96x96;
    case 128: return error_icon_128x128;
    case 160: return error_icon_160x160;
    case 196: return error_icon_196x196;
    default:
      return nullptr;
    }
  case ionizing_radiation_symbol:
    switch (size) {
    case 12: return ionizing_radiation_symbol_12x12;
    case 16: return ionizing_radiation_symbol_16x16;
    case 24: return ionizing_radiation_symbol_24x24;
    case 32: return ionizing_radiation_symbol_32x32;
    case 48: return ionizing_radiation_symbol_48x48;
    case 64: return ionizing_radiation_symbol_64x64;
    case 96: return ionizing_radiation_symbol_96x96;
    case 128: return ionizing_radiation_symbol_128x128;
    case 160: return ionizing_radiation_symbol_160x160;
    case 196: return ionizing_radiation_symbol_196x196;
    default:
      return nullptr;
    }
  case micro_sd_card_0deg:
    switch (size) {
    case 12: return micro_sd_card_0deg_12x12;
    case 16: return micro_sd_card_0deg_16x16;
    case 24: return micro_sd_card_0deg_24x24;
    case 32: return micro_sd_card_0deg_32x32;
    case 48: return micro_sd_card_0deg_48x48;
    case 64: return micro_sd_card_0deg_64x64;
    case 96: return micro_sd_card_0deg_96x96;
    case 128: return micro_sd_card_0deg_128x128;
    case 160: return micro_sd_card_0deg_160x160;
    case 196: return micro_sd_card_0deg_196x196;
    default:
      return nullptr;
    }
  case warning_icon:
    switch (size) {
    case 12: return warning_icon_12x12;
    case 16: return warning_icon_16x16;
    case 24: return warning_icon_24x24;
    case 32: return warning_icon_32x32;
    case 48: return warning_icon_48x48;
    case 64: return warning_icon_64x64;
    case 96: return warning_icon_96x96;
    case 128: return warning_icon_128x128;
    case 160: return warning_icon_160x160;
    case 196: return warning_icon_196x196;
    default:
      return nullptr;
    }
  case wi_time_10:
    switch (size) {
    case 12: return wi_time_10_12x12;
    case 16: return wi_time_10_16x16;
    case 24: return wi_time_10_24x24;
    case 32: return wi_time_10_32x32;
    case 48: return wi_time_10_48x48;
    case 64: return wi_time_10_64x64;
    case 96: return wi_time_10_96x96;
    case 128: return wi_time_10_128x128;
    case 160: return wi_time_10_160x160;
    case 196: return wi_time_10_196x196;
    default:
      return nullptr;
    }
  default:
    return nullptr;
  }
}

#endif