[package]
name = "bin2bmp"
version = "0.1.0"
edition = "2021"
authors = ["Alessandro Crugnola"]
description = "Convert ESP32 photo frame .bin files back to images"

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
image = "0.24.0"
anyhow = "1.0"
indicatif = "0.17.0"
