[package]
name = "bt_uploader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
console = "0.16.2"
crc32fast = "1.5.0"
indicatif = "0.18.3"
tokio = { version = "1.49.0", features = ["time", "rt-multi-thread"] }
uuid = { version = "1.20.0", features = ["v4"] }
photoframe-lib = { path = "../photoframe_lib" }
btleplug = "0.11.8"
